spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Indica a Hibernate di non toccare la struttura del DB (ci pensa schema.sql)
spring.jpa.hibernate.ddl-auto=none

# Indica a Spring di eseguire schema.sql all'avvio
spring.sql.init.mode=always

# Se usi H2, assicurati che il dialetto sia corretto
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect