spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Indica a Hibernate di non toccare la struttura del DB (ci pensa schema.sql)
spring.jpa.hibernate.ddl-auto=none

# Indica a Spring di eseguire schema.sql all'avvio
spring.sql.init.mode=always

# 3. Importante: Disabilita il tentativo di Hibernate di usare i LOB JDBC
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.hibernate.SQL=DEBUG
