spring.application.name=demo

# CONFIGURAZIONE DATABASE - PostgreSQL sempre attivo
# Le variabili d'ambiente Docker sovrascriveranno questi valori se presenti
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE CONFIGURATION  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Indica a Spring di eseguire schema.sql all'avvio
spring.sql.init.mode=always

# Importante: Disabilita il tentativo di Hibernate di usare i LOB JDBC
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.hibernate.SQL=DEBUG
