-- Tabella Utenti
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    ruolo VARCHAR(20) DEFAULT 'USER'
);

-- Tabella Libri
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    sottotitolo VARCHAR(255),
    autore VARCHAR(255),
    editore VARCHAR(255),
    anno_pubblicazione INT,
    isbn_10 VARCHAR(20),
    isbn_13 VARCHAR(20),
    formati VARCHAR(100),
    prezzo DOUBLE PRECISION,
    prezzo_originale DOUBLE PRECISION,
    stock INT,
    cover_url VARCHAR(500),
    valutazione_media DOUBLE PRECISION,
    numero_recensioni INT,
    categorie VARCHAR(255),
    tags VARCHAR(255),
    descrizione TEXT
);