-- Tabella Utenti
CREATE TABLE IF NOT EXISTS utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    ruolo VARCHAR(20) DEFAULT 'USER',
    attivo BOOLEAN DEFAULT TRUE,
    data_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabella Autori
CREATE TABLE IF NOT EXISTS autori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    biografia TEXT,
    -- Vincolo per evitare duplicati dello stesso autore
    CONSTRAINT unique_autore UNIQUE (nome, cognome)
);

-- Tabella Editori
CREATE TABLE IF NOT EXISTS editori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    sede VARCHAR(150) NOT NULL,
    -- Vincolo per evitare duplicati dello stesso editore
    CONSTRAINT unique_editore UNIQUE (nome)
);

-- Tabella Categorie
CREATE TABLE IF NOT EXISTS categorie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descrizione VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    descrizione VARCHAR(100) NOT NULL UNIQUE
);

-- Tabella Libri
CREATE TABLE IF NOT EXISTS libri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    sottotitolo VARCHAR(255),
    autore_id BIGINT NOT NULL,
    editore_id BIGINT NOT NULL,
    anno_pubblicazione INT NOT NULL,
    isbn10 VARCHAR(20),
    isbn13 VARCHAR(20) NOT NULL UNIQUE,
    formati VARCHAR(100),
    prezzo DOUBLE PRECISION NOT NULL,
    prezzo_originale DOUBLE PRECISION,
    stock INT DEFAULT 0 NOT NULL,
    copertinaUrl VARCHAR(500),
    valutazione_media DOUBLE PRECISION,
    numero_recensioni INT,
    categoria_id BIGINT NOT NULL,
    descrizione TEXT,
    
    -- Definizione dei vincoli di integrità
    CONSTRAINT fk_author FOREIGN KEY (autore_id) REFERENCES autori(id) ON DELETE RESTRICT,
    CONSTRAINT fk_publisher FOREIGN KEY (editore_id) REFERENCES editori(id) ON DELETE RESTRICT,
    CONSTRAINT fk_category FOREIGN KEY (categoria_id) REFERENCES categorie(id) ON DELETE RESTRICT,
    
    -- L'ISBN deve essere unico nel database
    CONSTRAINT unique_isbn13 UNIQUE (isbn13)
);

-- Tabella libro_tag (relazione molti-a-molti Book <-> Tag)
CREATE TABLE IF NOT EXISTS libro_tag (
    libro_id BIGINT,
    tag_id BIGINT,
    PRIMARY KEY (libro_id, tag_id),
    FOREIGN KEY (libro_id) REFERENCES libri(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- Tabella Carrello (un carrello per utente)
CREATE TABLE IF NOT EXISTS carrello (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrello_utente FOREIGN KEY (utente_id) REFERENCES utenti(id) ON DELETE CASCADE
);

-- Tabella Items del Carrello
CREATE TABLE IF NOT EXISTS carrello_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrello_id BIGINT NOT NULL,
    libro_id BIGINT NOT NULL,
    quantita INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_item_carrello FOREIGN KEY (carrello_id) REFERENCES carrello(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_libro FOREIGN KEY (libro_id) REFERENCES libri(id) ON DELETE RESTRICT,
    CONSTRAINT unique_carrello_libro UNIQUE (carrello_id, libro_id)
);

-- Tabella Ordini
CREATE TABLE IF NOT EXISTS ordini (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL,
    totale DOUBLE PRECISION NOT NULL,
    stato VARCHAR(50) DEFAULT 'COMPLETATO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ordine_utente FOREIGN KEY (utente_id) REFERENCES utenti(id) ON DELETE CASCADE
);

-- Tabella Items degli Ordini
CREATE TABLE IF NOT EXISTS ordini_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordine_id BIGINT NOT NULL,
    libro_id BIGINT NOT NULL,
    quantita INT NOT NULL,
    prezzo_unitario DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_ordine_item_ordine FOREIGN KEY (ordine_id) REFERENCES ordini(id) ON DELETE CASCADE,
    CONSTRAINT fk_ordine_item_libro FOREIGN KEY (libro_id) REFERENCES libri(id) ON DELETE RESTRICT
);