-- Tabella Utenti
CREATE TABLE IF NOT EXISTS utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    ruolo VARCHAR(20) DEFAULT 'USER'
);

-- Tabella Autori
CREATE TABLE IF NOT EXISTS autori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    biografia TEXT,
    -- Vincolo per evitare duplicati dello stesso autore
    CONSTRAINT unique_autore UNIQUE (nome, cognome)
);

-- Tabella Editori
CREATE TABLE IF NOT EXISTS editori (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    sede VARCHAR(150) NOT NULL,
    -- Vincolo per evitare duplicati dello stesso editore
    CONSTRAINT unique_editore UNIQUE (nome)
);
-- Tabella Libri
CREATE TABLE IF NOT EXISTS libri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    sottotitolo VARCHAR(255),
    autore_id INT NOT NULL,
    editore_id INT NOT NULL,
    anno_pubblicazione INT NOT NULL,
    isbn10 VARCHAR(20),
    isbn13 VARCHAR(20) NOT NULL UNIQUE,
    formati VARCHAR(100),
    prezzo DOUBLE PRECISION NOT NULL,
    prezzo_originale DOUBLE PRECISION,
    stock INT DEFAULT 0 NOT NULL,
    cover_url VARCHAR(500),
    valutazione_media DOUBLE PRECISION,
    numero_recensioni INT,
    categoria VARCHAR(255) NOT NULL,
    tags VARCHAR(255),
    descrizione TEXT,
    
    -- Definizione dei vincoli di integrità
    CONSTRAINT fk_author FOREIGN KEY (autore_id) REFERENCES autori(id) ON DELETE RESTRICT,
    CONSTRAINT fk_publisher FOREIGN KEY (editore_id) REFERENCES editori(id) ON DELETE RESTRICT,
    
    -- L'ISBN deve essere unico nel database
    CONSTRAINT unique_isbn13 UNIQUE (isbn13)
);